language: node_js
sudo: false
node_js:
  - 8
addons:
  apt:
    packages:
      - google-chrome-stable
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn run lint
  - lerna bootstrap --ignore={benchmarks,demos}
  - lerna run pretest --ignore={benchmarks,demos}
  - lerna run test --ignore={benchmarks,demos} --concurrency=1
  - yarn run tsc
  - lerna run prepublish --ignore={benchmarks,demos}
